Repository mindera-school/MS5-To-Do-List, pull requests merged in 2023-02, with the labels that each got.

#39 Add: drag to organize
  script.js
Labels: FE

#41 add sass and darkmode mixin
  .gitignore
  FE/src/background-images/darkmodebg.jpg
  FE/src/background-images/lightmodebg.jpg
  FE/src/icons/check.svg
  FE/src/icons/delete.svg
  FE/src/icons/edit.svg
  FE/src/icons/menu.svg
  FE/src/icons/plus-circle.svg
  FE/src/icons/trash.svg
  FE/src/icons/user.svg
  FE/src/index.html
  FE/src/script.js
  FE/src/stylesheets/_animations.scss
  FE/src/stylesheets/output.css
  FE/src/stylesheets/output.css.map
  FE/src/stylesheets/style.css
  FE/src/stylesheets/style.scss
  index.html
Labels: Fix

#55 Add: BE folder and structure
  BE/toDoListAPI/.gitignore
  BE/toDoListAPI/.mvn/wrapper/maven-wrapper.properties
  BE/toDoListAPI/docker-compose.yml
  BE/toDoListAPI/mvnw
  BE/toDoListAPI/mvnw.cmd
  BE/toDoListAPI/pom.xml
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/ToDoListApiApplication.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/repository/ToDoRepository.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/service/UserService.java
  BE/toDoListAPI/src/main/resources/application.properties
  BE/toDoListAPI/src/test/java/shcool/mindera/toDoListAPI/ToDoListApiApplicationTests.java
Labels: enhancement, BE

#56 #27 add a sidebar menu to login
  FE/index.html
  FE/src/assets/background-images/darkmodebg.jpg
  FE/src/assets/background-images/lightmodebg.jpg
  FE/src/assets/icons/arrow-right-svgrepo-com.svg
  FE/src/assets/icons/check.svg
  FE/src/assets/icons/delete.svg
  FE/src/assets/icons/edit.svg
  FE/src/assets/icons/menu.svg
  FE/src/assets/icons/plus-circle.svg
  FE/src/assets/icons/trash.svg
  FE/src/assets/icons/user-add-svgrepo-com.svg
  FE/src/assets/icons/user.svg
  FE/src/scripts/components/loginSideBar.js
  FE/src/scripts/script.js
  FE/src/stylesheets/output.css
  FE/src/stylesheets/output.css.map
  FE/src/stylesheets/style.css
  FE/src/stylesheets/style.scss
Labels: enhancement, question, FE

#59 20 add dark mode
  FE/index.html
  FE/src/assets/icons/delete-light-theme.svg
  FE/src/assets/icons/delete-navy-theme.svg
  FE/src/scripts/components/loginSideBar.js
  FE/src/stylesheets/_darkModeClasses.scss
  FE/src/stylesheets/_darkmodeSlider.scss
  FE/src/stylesheets/output.css
  FE/src/stylesheets/output.css.map
  FE/src/stylesheets/style.scss
Labels: enhancement, FE, MVP

#60 Add: All DTOs
  .idea/.gitignore
  .idea/MS5-To-Do-List.iml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOComment.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOGroup.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOLoggedUser.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOLogin.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTONewComment.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTONewFollow.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTONewGroup.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTONewTag.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTONewTask.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTORegister.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOTag.java
  BE/toDoListAPI/src/main/java/shcool/mindera/toDoListAPI/model/DTOTask.java
Labels: enhancement, BE
