Repository mindera-school/MS5-To-Do-List, pull requests merged in 2023-03, with the labels that each got.

#87 Repositories interfaces-creation
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/CommentsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/GroupsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TagsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TaskTagsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TasksRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/UsersRepository.java
Labels: enhancement, BE

#90 Users endpoints basic implementation
  BE/toDoListAPI/pom.xml
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/UsersEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOLoggedUser.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOLogin.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTORegister.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/UsersRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
  BE/toDoListAPI/src/main/resources/application.yml
Labels: enhancement, BE

#93 Refactor group/tasks
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/CommentsEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/FollowersEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/GroupsEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/TagsEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/TasksEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/UsersEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/compositePrimaryKeys/FollowersId.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/GroupsRepository.java
  BE/toDoListAPI/src/main/resources/application.yml
Labels: enhancement, BE

#94 92 tag implementation
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TagController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/TaskTagsEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/TasksEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/UsersEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTONewTag.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOTaskPreview.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TagsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TaskTagsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TasksRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
  BE/toDoListAPI/src/main/resources/application.yml
Labels: enhancement, BE

#102 add pull request template
  .github/pull_request_template/pull_request_template.md
Labels: documentation, enhancement

#110 Task getters
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TaskController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/Converter.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOTaskDetails.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/TasksRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
Labels: enhancement, BE

#112 add: patch to change profile image
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOChangeImg.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
Labels: enhancement, BE

#111 Login drawer
  FE/.vscode/settings.json
  FE/src/App.js
  FE/src/assets/icons/calendar-darkmode.svg
  FE/src/assets/icons/calendar.svg
  FE/src/assets/icons/heart.svg
  FE/src/assets/icons/maximize-darkmode.svg
  FE/src/assets/icons/maximize.svg
  FE/src/assets/icons/move-darkmode.svg
  FE/src/assets/icons/move.svg
  FE/src/components/AccountMenus/LoginMenu/index.jsx
  FE/src/components/AccountMenus/LoginMenu/styled-components.js
  FE/src/components/AccountMenus/MenuContainer/index.jsx
  FE/src/components/AccountMenus/RegisterMenu/index.jsx
  FE/src/components/AccountMenus/RegisterMenu/styles.js
  FE/src/components/AccountMenus/UserProfile/index.jsx
  FE/src/components/AccountMenus/UserProfile/styles.js
  FE/src/components/AccountMenus/index.js
  FE/src/components/Drawer/index.jsx
  FE/src/components/Drawer/styled-components.js
  FE/src/components/Header/index.jsx
  FE/src/components/TaskPreview/index.jsx
  FE/src/components/TaskPreview/styled-components.js
  FE/src/components/index.js
  FE/src/configs/accountMenu.jsx
  FE/src/context.js
Labels: FE

#113 Get comments
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/CommentController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/Converter.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOComment.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/CommentsRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/CommentService.java
Labels: BE

#115 Edited file settings.json and added extensions.json
  FE/.vscode/extensions.json
  FE/.vscode/settings.json
Labels: FE

#125 Fix: header
  FE/src/components/Header/index.jsx
  FE/src/components/Header/styled-component.js
Labels: FE

#126 Fix Security, implementation and Configuration of CORS
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/ToDoListApiApplication.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTORegister.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/security/CorsFilter.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/security/SecurityConfig.java
  FE/src/components/AccountMenus/RegisterMenu/index.jsx
Labels: bug, BE

#130 Create tasks
  FE/src/App.js
  FE/src/GlobalStyles.js
  FE/src/components/AddTaskModal/index.jsx
  FE/src/components/AddTaskModal/style.js
  FE/src/components/CreateTasks/index.jsx
  FE/src/components/CreateTasks/style.js
  FE/src/components/CreateTasksContainer/index.jsx
  FE/src/components/CreateTasksContainer/style.js
  FE/src/components/Header/index.jsx
  FE/src/context.js
Labels: enhancement, FE

#131 Fix date value
  FE/src/components/CreateTasksContainer/index.jsx
Labels: bug, FE
