Repository mindera-school/MS5-To-Do-List, pull requests merged in 2023-04, with the labels that each got.

#138 Refactor task patch
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/CommentController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TagController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TaskController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOChangeImg.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOForgotPassword.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOLoggedUser.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOUpdatePosition.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOUpdateTask.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
  wiki/DTOs.md
Labels: bug, enhancement, BE

#145 Add filter by tag
  FE/src/App.js
  FE/src/components/AddTasks/AddTaskModal/style.js
  FE/src/components/LeftMenu/index.jsx
  FE/src/components/LeftMenu/style.js
  FE/src/components/Tag/styled-components.js
  FE/src/components/TaskDetailsModal/index.jsx
  FE/src/components/TaskTagsList/index.jsx
Labels: FE

#148 Add border colors to tasks
  FE/src/components/AddTasks/CreateTasksContainer/index.jsx
  FE/src/components/TaskPreview/index.jsx
  FE/src/components/TaskPreview/styled-components.js
Labels: FE

#151 Feat change position be
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TaskController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/Converter.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTONewTask.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOUpdateTask.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
  wiki/DTOs.md
Labels: enhancement, BE

#152 Comments exceptions
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/comments/CommentNotFoundException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/comments/CommentsExceptionHandler.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/CommentService.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
  FE/src/components/AddTasks/CreateTasksContainer/index.jsx
Labels: enhancement, BE

#155 User Register endpoint refactor
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
Labels: bug, BE

#154 fix: add tasks is now fixed
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
  FE/src/components/AddTasks/AddTaskModal/index.jsx
  FE/src/components/AddTasks/CreateTasksContainer/index.jsx
Labels: bug, BE, FE

#153 Regex
  FE/src/components/AccountMenus/RegisterMenu/index.jsx
  FE/src/components/AccountMenus/RegisterMenu/styles.js
Labels: enhancement, FE, MVP, Login System

#156 Add subtasks
  FE/src/components/TaskList/index.jsx
  FE/src/components/TaskPreview/SubtaskList.jsx
  FE/src/components/TaskPreview/index.jsx
  FE/src/components/TaskPreview/styled-components.js
Labels: enhancement, FE

#157 Tags exception
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/comments/CommentNotFoundException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tags/TagNotFoundException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tags/TagsExceptionHandler.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
Labels: enhancement, BE

#158 Task exceptions
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/InvalidTaskException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tasks/InvalidTaskException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tasks/TaskMissingDataException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tasks/TaskNotFoundException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tasks/TasksExceptionHandler.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/user/UserExceptionHandler.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOTaskPreview.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/CommentService.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TaskService.java
Labels: enhancement, BE

#159 Add tag refactor
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TagController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tags/TagAlreadyInUseException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/tags/TagsExceptionHandler.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/Converter.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
  wiki/DTOs.md
Labels: enhancement, BE

#164 fix: missing dispatch on addTask method
  FE/src/components/AddTasks/AddTaskModal/index.jsx
Labels: bug, FE

#161 Double click
  FE/src/components/TaskDetailsModal/index.jsx
  FE/src/components/TaskPreview/index.jsx
Labels: enhancement, FE, MVP

#168 Update Endpoint Implementation
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TagController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/TagService.java
Labels: enhancement, BE

#171 UPDATE Tags add on WIKI
  wiki/DTOs.md
Labels: WIKI

#165 Add tags
  FE/src/components/AddTasks/AddTaskModal/index.jsx
  FE/src/components/AddTasks/CreateTasksContainer/index.jsx
  FE/src/components/Tag/index.jsx
  FE/src/components/Tag/styled-components.js
  FE/src/components/TagsList/index.jsx
  FE/src/components/TagsList/style.js
  FE/src/components/TaskDetailsModal/index.jsx
  FE/src/components/TaskList/index.jsx
  FE/src/components/TaskPreview/index.jsx
  FE/src/components/TaskTagsList/index.jsx
Labels: FE

#170 Save user
  FE/src/context.js
Labels: enhancement, FE, Login System

#181 Fix date and checkbox bugs
  FE/src/components/AddTasks/AddTaskModal/index.jsx
  FE/src/components/AddTasks/AddTaskModal/style.js
  FE/src/components/AddTasks/CreateTasksContainer/index.jsx
  FE/src/components/TaskDetailsModal/index.jsx
  FE/src/components/TaskPreview/index.jsx
Labels: bug, FE

#189 Edit refact endpoint
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/UsersEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOEditUser.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
Labels: enhancement, BE

#191 Handle reset password confirmation
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOChangePassword.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/repositories/CodesRepository.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
Labels: enhancement, BE

#197 Corrections
  BE/toDoListAPI/pom.xml
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/CommentController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TagController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/TaskController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/controller/UserController.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/entities/UsersEntity.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/user/UserExceptionHandler.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/exceptions/user/UsersPasswordIsInvalidException.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/model/DTOLoggedUser.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/UserService.java
  BE/toDoListAPI/src/main/java/school/mindera/toDoListAPI/service/emailhandler/EmailFactory.java
  BE/toDoListAPI/src/test/java/school/mindera/toDoListAPI/ToDoListApiApplicationTests.java
  BE/toDoListAPI/src/test/java/school/mindera/toDoListAPI/service/UserServiceTest.java
  FE/src/App.js
  FE/src/pages/forgotpasspage-components.js
Labels: bug, enhancement, BE
